project:
  type: website

resources:
  - CNAME

website:
  title: "Omid Rohanian"
  description: "Omid Rohanian is a Senior Research Associate at the University of Oxford specialising in NLP and biomedical AI."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bio
        text: Bio
      - href: papers/index.qmd
        text: Papers
      - href: posts/index.qmd
        text: Blog
      # - href: talks/index.qmd
      #   text: Talks

  page-footer:
    left: "Omid Rohanian [Disclaimer](disclaimer/index.qmd)"
  twitter-card: true
  open-graph: true
  google-analytics: "395640625"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>
        {
          "@context": "http://www.schema.org",
          "@type": "Person",
          "name": "Omid Rohanian",
          "jobTitle": "Senior Research Associate, NLP & Biomedical AI",
          "description": "Omid Rohanian is a Senior Research Associate at the University of Oxford specializing in natural language processing, biomedical text analysis, and compact transformer models.",
          "url": "https://omidrohanian.github.io",
          "image": "https://omidrohanian.github.io/img/minialbert.jpg",
          "address": {
            "@type": "PostalAddress",
            "addressLocality": "Oxford",
            "addressRegion": "OX",
            "addressCountry": "United Kingdom"
          },
          "alumniOf": [
            {"@type": "CollegeOrUniversity","name": "University of Oxford"},
            {"@type": "CollegeOrUniversity","name": "University of Wolverhampton"},
            {"@type": "CollegeOrUniversity","name": "Sharif University of Technology"}
          ],
          "worksFor": [
            {"@type": "Organization","name": "University of Oxford"}
          ],
          "nationality": [
            {"@type": "Country","name": "United Kingdom"}
          ]
        }
        </script>
