project:
  type: website

website:
  title: "Omid Rohanian"
  description: "Research in computational linguistics & biomedical NLP"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: _posts/

format:
  html:
    theme: flatly
    css: styles.css
    code-fold: true
    df-print: paged

publish:
  gh-pages:
    branch: gh-pages
    publish-dir: _site
